---

- name: "~/fileserver exists"
  tags: [ui, nginx]
  file:
    path: "~/fileserver"
    state: directory

- name: copy ../dist/spa to ~/fileserver/
  tags: [start,files, copy_ui]
  copy:
    src: ../dist/spa
    dest: ~/fileserver/


- name: copy pollofeed.com to ~/fileserver/vhost.d/
  tags: [start]
  copy:
    src: pollofeed.com
    dest: ~/fileserver/vhost.d/

- name: copy pollofeed.com_location to ~/fileserver/vhost.d/
  tags: [start]
  copy:
    src: pollofeed.com_location
    dest: ~/fileserver/vhost.d/

- name: copy lightningAddr.json to ~/fileserver/spa/
  tags: [start]
  copy:
    src: lightningAddr.json
    dest: ~/fileserver/spa/


- name: start nginx container
  command: docker-compose up -d fileserver
  tags: start
  args:
    chdir: "./{{APP_DIR}}"

- name: reload nginx
  tags: [start]
  command: docker exec -it nginx nginx -s reload
