---
- hosts: localhost
  tags: build
  gather_facts: no
  tasks:
    - name: yarn install
      command: yarn install
      args:
        chdir: ..
    - name: npm run build:web
      command: npm run build:web
      args:
        chdir: ..
#    - name: zip dist
#      command: zip ../spa.zip ../dist/spa/

- hosts: pollofeed
#  vars_files:
#    - default.config.yml
  tags: deploy
#  become: yes
  roles:
    - pollofeed


