name: web app

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        run: npm i
      - name: lint
        run: npm run lint
      - name: build web app
        run: npm run build:web

#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: npm-${{ hashFiles('package-lock.json') }}
#          restore-keys: npm-
#
#      - name: Install dependencies
#        run: npm ci --ignore-scripts

      # run npm test, build, lint, etc.
