name: build

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.6'
      - name: install dependencies
        run: npm i
      - name: build web app
        run: npm run build:web
