name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: build and deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          directory: playbooks
          requirements: requirements.yml
          options: -v
          inventory: |
            [pollofeed]
            ${{ secrets.DEPLOY_HOST }} ansible_user=${{ secrets.SSH_USER }} ansible_port=${{ secrets.SSH_PORT }}
