name: Deploy

on:
  push:
    branches:
      - test/deploy

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          #          known_hosts: ${{env.SSH_KNOWN_HOSTS}}
          directory: playbooks
          #          vault_password: test
          requirements: requirements.yml
          options: -v
          inventory: |
            [pollofeed]
            pollofeed.com ansible_user=joe
