name: invoice

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour at min 0
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.6'
      - name: install dependencies
        run: npm i
      - name: npm run cypress:invoice
        env:
          CYPRESS_BASE_URL: https://pollofeed.com
        run: npm run cypress:invoice
